#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# patch28: record the DOI. Zenodo archived the first release and issued a
# permanent identifier, so the citation now survives this repository moving or
# disappearing. Adds the doi to CITATION.cff, a badge row to the README, and a
# short section stating how to cite the register and how to cite a single row.
# Run this inside the mcp-conduct-register checkout.
# Default is dry-run. --apply writes. Anchors expect exactly 1 hit each.
import sys, os

APPLY = "--apply" in sys.argv
EDITS = [('CITATION.cff', 'repository-code: "https://github.com/ogasurfproject-jpg/mcp-conduct-register"', 'doi: "10.5281/zenodo.21970931"\nrepository-code: "https://github.com/ogasurfproject-jpg/mcp-conduct-register"', 'citation doi field'), ('README.md', '# MCP Conduct Register\n\n**MCP Conduct Register is a machine generated public record of how Model Context Protocol servers', '# MCP Conduct Register\n\n[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.21970931.svg)](https://doi.org/10.5281/zenodo.21970931)\n[![Rebuilt daily from a public API](https://img.shields.io/badge/rebuilt-daily%20from%20a%20public%20API-2f6feb)](https://gate.horizonshield.dev/register)\n[![Rows chosen by](https://img.shields.io/badge/rows%20chosen%20by-nobody-6e7681)](https://github.com/ogasurfproject-jpg/mcp-conduct-register/blob/main/scripts/build_register.py)\n[![Atom feed](https://img.shields.io/badge/feed-atom-e36209)](https://raw.githubusercontent.com/ogasurfproject-jpg/mcp-conduct-register/main/feed.xml)\n[![License MIT](https://img.shields.io/badge/license-MIT-2ea043)](https://opensource.org/licenses/MIT)\n\n**MCP Conduct Register is a machine generated public record of how Model Context Protocol servers', 'readme badges'), ('README.md', '## Questions people actually ask', '## How to cite this register\n\nArchived on Zenodo with a permanent identifier, so a citation survives this repository moving or\ndisappearing.\n\n```\nOga, Toshikatsu (2026). MCP Conduct Register: a machine generated register of measured MCP server\nconduct. Zenodo. https://doi.org/10.5281/zenodo.21970931\n```\n\nBibTeX and APA forms are generated by the "Cite this repository" button on GitHub, which reads\n`CITATION.cff`. The author is identified by ORCID 0009-0000-9180-903X, so this register sits in the\nsame record as the open dataset and the preprints it was built from.\n\nWhen citing a single row rather than the register, cite the endpoint\'s history URL and the\n`record_sha256` of the verdict you are relying on. That pair is enough for a reader to recompute the\nrecord and confirm you quoted it correctly.\n\n## Questions people actually ask', 'readme citation section')]
DOI = "10.5281/zenodo.21970931"

def main():
    if not os.path.exists("CITATION.cff"):
        print("ABORT: run this inside the mcp-conduct-register checkout.")
        sys.exit(1)
    contents = {}
    ok = True
    for path, old, new, name in EDITS:
        if path not in contents:
            contents[path] = open(path, encoding="utf-8").read()
        n = contents[path].count(old)
        print("[anchor] %s: %d occurrence(s) (expect 1)" % (name, n))
        if n != 1: ok = False
    if not ok:
        print("ABORT: anchor mismatch. Nothing written.")
        sys.exit(1)
    for path, old, new, name in EDITS:
        contents[path] = contents[path].replace(old, new, 1)

    cit = contents["CITATION.cff"]
    rd = contents["README.md"]
    checks = [
        (cit.count("doi:") == 1, "citation: exactly one doi field"),
        (DOI in cit, "citation: doi value present"),
        (rd.count(DOI) == 3, "readme: doi in badge link and citation block"),
        ("How to cite this register" in rd, "readme: citation section present"),
        ("record_sha256" in rd, "readme: explains citing a single row"),
        ("<!-- REGISTER:START -->" in rd and "<!-- REGISTER:END -->" in rd, "readme: generator markers intact"),
        ("rows%20chosen%20by-nobody" in rd, "readme: provenance badge present"),
    ]
    try:
        import yaml
        d = yaml.safe_load(cit)
        checks.append((d.get("doi") == DOI, "citation: parses as yaml with the doi"))
        checks.append((bool(d.get("authors")), "citation: authors intact"))
    except ImportError:
        checks.append((True, "citation: yaml module absent, skipped parse check (not a failure)"))
    except Exception as e:
        checks.append((False, "citation: yaml INVALID :: %s" % e))
    allok = True
    for good, label in checks:
        print(("[ok]  " if good else "[FAIL] ") + label)
        allok = allok and good
    if not allok:
        print("ABORT: invariant failed. Nothing written.")
        sys.exit(1)
    if not APPLY:
        print("DRY-RUN OK. Nothing written. Run with --apply to write.")
        return
    for path in contents:
        open(path, "w", encoding="utf-8").write(contents[path])
        print("[written] " + path)
    print("APPLY done. Commit and push. No new release needed for this change.")

if __name__ == "__main__":
    main()
